### ISSUE TITLE
How to change metrics interval?

### ISSUE THREAD

**Issue by luizbizzio** [rkosegi/tuya-smartplug-exporter#40]
How could I change the metrics interval? It seens is 10s..

**Comment by rkosegi** [comment]
Hi,

this exporter itself is stateless. When there is requests, it go over all configured devices and ask them for their values.
It does not cache anything.

Scraping configuration is usually done in Prometheus.
Here is an example of such config, where exporter is scrapped every minute:

```
scrape_configs:
- job_name: power_consumption
  honor_labels: true
  scrape_interval: 1m
  static_configs:
  - targets: ['192.168.1.10:9999']

```
